![sslogo](https://github.com/stratascratch/stratascratch.github.io/raw/master/assets/sslogo.jpg)

# Intro to NumPy (Numerical Python)

NumPy is the fundamental package for scientific computing in Python. NumPy is used in many other packages in python even though you may not see it explicitly running in your code.

It is a python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python, so time spent learning to use NumPy effectively will be valuable no matter what aspect of data science interests you.




## Lists in Python

- Natively built into python and doesn't require you to import libraries to use the functionality
- Lists are great to store values collectively and retrieve data easily

#### We can create list of integers

In [2]:
#manual way of creating lists
A = [10, 11, 12, 13, 14]

In [3]:
#create lists using functions
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [14]:
#find the data type of a list
print(type(L[0]))
print(type(L))

<class 'int'>
<class 'list'>


#### We can create a list of strings

In [5]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [6]:
type(L2[0])

str

#### We can create heterogeneous lists

In [18]:
L3 = [True, "2", 3.0, 4]
#get type(item) of the array
[type(item) for item in L3]
[item for item in L3]
  

[True, '2', 3.0, 4]

## Arrays in Python

What is an array?

- An array is a data structure that allows you to store values...like a list

How is it different than a list?
- An array is more efficient at storing large amounts of data
- Easy and simple to perform numerical/math operations

### Creating Arrays From Python Lists

#### Import the numpy package using np as an alias

In [8]:
import numpy as np

#### Use np.array to create arrays from Python lists

In [9]:
# integer array
listA = [1,4,2,5,3]
numpyarrayA = np.array(listA)
numpyarrayA

array([1, 4, 2, 5, 3])

#### Numpy is constrained to arrays that all contain the same type. If the types do not match, NumPy will try to change the data type

In [10]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

#### Numpy allows you to make multidimensional arrays using lists of lists

In [24]:
x = np.array([[1, 2], 
          [3, 4],
          [3, 3]])
x

array([[1, 2],
       [3, 4],
       [3, 3]])

### Creating Arrays from Scratch

#### Especially for larger arrays, it's more efficient to create arrays from scratch using functions built into NumPy

In [27]:
# create an integer array with 10 zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [32]:
# create a 3x5 float-ing point array filled with 1s
np.ones((3,5), dtype=float)
#np.ones((3,5), 2)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# create a 3x5 array filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [ ]:
# create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
# create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [37]:
# create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[0.96067367, 0.41899959, 0.94571406],
       [0.96193921, 0.74870974, 0.55271935],
       [0.77978095, 0.426486  , 0.72560393]])

In [41]:
# create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
# np.random.normal(mean,std,array size)

np.random.normal(0, 7, (3, 3))

array([[-0.79560267,  4.10487674,  0.13901111],
       [ 5.30976554, -1.10800539, -7.56479326],
       [ 7.13609521, -4.29777859, -0.55674695]])

In [43]:
# create a 3x3 array of random integers in the interval [0, 10)
# np.random.randint(start value, stop value, array size)
np.random.randint(0, 21, (5,5))

array([[19,  0,  3, 11, 18],
       [20, 14,  4, 18, 12],
       [13, 20, 15,  1,  0],
       [ 6,  0,  4, 17,  9],
       [16, 12, 19, 14, 13]])

In [45]:
# create a 3x3 identity matrix
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
# create an uninitialized array of three integers
# the values will be whatever happens to already exist at that memory location
np.empty(6)

array([1.54032090e-316, 0.00000000e+000, 6.92628234e-310, 6.92628234e-310,
       4.03259187e+175, 8.54400435e-072])

## NumPy Standard Data Types

NumPy arrays contain values of a single type, so it is important to have detailed knowledge of those types and their limitations.
Because NumPy is built in C, the types will be familiar to users of C, Fortran, and other related languages.

The standard NumPy data types are listed in the following table.
Note that when constructing an array, they can be specified using a string:

```python
np.zeros(10, dtype='int16')
```

Or using the associated NumPy object:

```python
np.zeros(10, dtype=np.int16)
```

In [49]:
a = np.zeros(10, dtype='int16')
a

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [51]:
a.dtype

dtype('int16')

| Data type	    | Description |
|---------------|-------------|
| ``bool_``     | Boolean (True or False) stored as a byte |
| ``int_``      | Default integer type (same as C ``long``; normally either ``int64`` or ``int32``)| 
| ``intc``      | Identical to C ``int`` (normally ``int32`` or ``int64``)| 
| ``intp``      | Integer used for indexing (same as C ``ssize_t``; normally either ``int32`` or ``int64``)| 
| ``int8``      | Byte (-128 to 127)| 
| ``int16``     | Integer (-32768 to 32767)|
| ``int32``     | Integer (-2147483648 to 2147483647)|
| ``int64``     | Integer (-9223372036854775808 to 9223372036854775807)| 
| ``uint8``     | Unsigned integer (0 to 255)| 
| ``uint16``    | Unsigned integer (0 to 65535)| 
| ``uint32``    | Unsigned integer (0 to 4294967295)| 
| ``uint64``    | Unsigned integer (0 to 18446744073709551615)| 
| ``float_``    | Shorthand for ``float64``.| 
| ``float16``   | Half precision float: sign bit, 5 bits exponent, 10 bits mantissa| 
| ``float32``   | Single precision float: sign bit, 8 bits exponent, 23 bits mantissa| 
| ``float64``   | Double precision float: sign bit, 11 bits exponent, 52 bits mantissa| 
| ``complex_``  | Shorthand for ``complex128``.| 
| ``complex64`` | Complex number, represented by two 32-bit floats| 
| ``complex128``| Complex number, represented by two 64-bit floats| 